---
title: "1_CDS_prediction_convert"
author: "Min-Yao"
date: "8/23/2021"
output: html_document
---

```{r}
library(tidyverse)
library(magrittr)
library(Biostrings)
library(GenomicRanges)
library(rtracklayer)
```


## Intro

Want to use ML to predict coding and non coding sequences

First need to figure out how to code each base as coding or not

## download and import files

```{r}
timestamp()
```


```{r}
# if (!dir.exists("AtSeqs")) {
#   dir.create("AtSeqs")
#   download.file("ftp://ftp.arabidopsis.org/home/tair/Maps/gbrowse_data/TAIR10/TAIR10_GFF3_genes.gff", "AtSeqs/TAIR10_GFF3_genes.gff")
#   download.file("ftp://ftp.arabidopsis.org/home/tair/Sequences/whole_chromosomes/TAIR10_chr1.fas", "AtSeqs/TAIR10_chr1.fas")
# }
```

```{r}
# rtracklayer
gff <- import.gff("AtSeqs/TAIR10_GFF3_genes.gff")
gff
```

```{r}
Chr1 <- readDNAStringSet("AtSeqs/TAIR10_chr1.fas")
str(Chr1)
head(Chr1)
```

1 base per row
```{r}
# each cell has one base in it
chr1.tib <- as.matrix(Chr1) %>% t() %>%
  as_tibble() %>%
  rename_with(~ str_remove(.," .*")) %>%
  mutate(pos=1:nrow(.))
head(chr1.tib)
```
create gff for just the CDS
```{r}
gffCDS <- gff[gff$type=="CDS",]
gffCDS
```
### 1) update code to focus on + strand only
query the CDS
```{r}
# First create a query Granges, one per base and + strand only
chr1.query <- GRanges(seqnames = "Chr1", ranges=IRanges(start = chr1.tib$pos, width = 1), strand="+")

chr1.tib$CDS <- findOverlaps(chr1.query, gffCDS, select = "first", ignore.strand=TRUE) %>%
  is.na() %>%
  not() %>% # reverse false and true
  as.integer()
```

```{r}
chr1.tib
```

take a look at the first 10 coding bases:
```{r}
chr1.tib %>% filter(CDS==1) %>%
  extract(1:10,)
```

```{r}
rm(chr1.query, gff, Chr1, gffCDS)
gc()
```

### 2) make one hot encoding for base (or possibly codon)

```{r}
system.time(
  chr1.1_hot <- chr1.tib %>%
    pivot_wider(values_from = Chr1, 
                names_from = Chr1, 
                values_fn = function(x) 1L, #integer (less space)
                values_fill = 0L)
)

head(chr1.1_hot)
```
> Y = Cytosine / Thymine (pyrimidine)

```{r}
system.time(write_csv(chr1.1_hot, file="AtSeqs/chr1_1_hot_plus_strand_all.csv.gz"))
```